JuliaData/IndexedTables.jl

src/NDSparseData.jl
src/query.jl

SQL like queries on NDSparse arrays. I think a generalized (outer, inner, theta etc.) join can also be done, but it feels awkward using column indices instead of column names. 
Here's a demo:
```julia
a = NDSparse([12,21,32], [52,41,34], [11,53,150])
b = NDSparse([12,23,32], [52,43,34], [56,13,10])
naturaljoin(a, b, +)
select(a, 1=>x->x<30, 2=>x->x>40)
filter(x->x>100, a)
```
cc @shashi

WIP: Queries on NDSparse

---

benchmarks/run.jl
src/NDSparseData.jl
src/query.jl
src/utils.jl
test/test_core.jl

I think we will be better off without storing a default value for each array. It wasn't clear what the default value means in full generality, and only `map` was actually using it. Instead, we can use standard joins, and with this change `map` and `naturaljoin` do the same thing so we don't need both. Also, some data types do not have obvious default values.

RFC: remove stored default value

---

REQUIRE
src/NDSparseData.jl
src/columns.jl
src/query.jl
src/utils.jl

The approach is (1) use `Columns` for both indexes and data, (2) bring in NamedTuples. Example:
```
julia> NDSparse(rand(3), Columns(open = rand(3), close = rand(3)))
NDSparse{NDSparseData._NT_openclose{Float64,Float64},Tuple{Float64}}:
(0.07459099981805961,) => (open => 0.39695970629326216, close => 0.8768181865079363)
(0.23068405270544878,) => (open => 0.21901570490914923, close => 0.9516909318576521)
(0.8329699883751216,) => (open => 0.23058501858024938, close => 0.8031837612378654)
```

add NamedTuple support for named columns and struct-of-arrays data

---

README.md
benchmark/benchmarks.jl
src/IndexedTables.jl
src/indexing.jl
src/join.jl
src/query.jl
test/test_core.jl
test/test_query.jl
test/test_utils.jl

Here's a suggested solution to the naming quandary.
- Make `IndexedTable` the canonical name
- a binding deprecation for `NDSparse`
- Provide `Table` as an optional alias. If you're only using IndexedTables, you can do `using IndexedTables.Table` for convenience.

rename `NDSparse` to `IndexedTable`

---

REQUIRE
src/utils.jl

This should be the only thing left to do so that the package can be registered (JuliaLang/METADATA.jl#8476).
The REQUIRE bound on ``NamedTuples`` is not ideal, the proper requirement would be ``2.1.0`` if you are on ``2.x``, or ``3.0.2`` if you are on ``3.x``. But I don't think that kind of requirement can be written, so this is probably the best we can do.

Remove map for NamedTuple

---

src/query.jl
test/test_query.jl

This makes it a bit nicer to perform multiple aggregations on groups.
```julia
tbl = NDSparse(rand(1:3, 10), rand(1:2, 10), rand(10))
aggregate_vec(tbl, max = maximum, q75 = x->quantile(x, 0.75))
```
I included two versions, one with Pairs and one with keyword arguments. I like the keyword arg version better.

RFC: Add a kw-arg method to aggregate_vec

---

src/join.jl
test/test_core.jl

Sometimes some chunks may not contain missing values in some columns, but may in others. Or some chunks may be all Integers and some may have floats. In such cases we need to promote the output columns type while doing a `merge`.

promote_similar for output data columns in merge

---

src/IndexedTables.jl
src/columns.jl
test/test_core.jl

This was breaking [this line](https://github.com/JuliaComputing/IndexedTables.jl/blob/master/src/join.jl#L132) because the call to similar above doesn't specify a length.

similar(::Columns) should return a Columns of the same size

---

.travis.yml
REQUIRE
src/columns.jl
src/utils.jl
test/test_core.jl

```julia
julia> c = Columns(x=[1,2],y=[2.,4])
2-element IndexedTables.Columns{NamedTuples._NT_x_y{Int64,Float64},NamedTuples._NT_x_y{Array{Int64,1},Array{Float64,1}}}:
(x = 1, y = 2.0)
(x = 2, y = 4.0)
julia> pick(:y)(c)
2-element Array{Float64,1}:
2.0
4.0
julia> pick(:y)(c)
2-element Array{Float64,1}:
2.0
4.0
julia> pick((:y,))(c)
2-element IndexedTables.Columns{NamedTuples._NT_y{Float64},NamedTuples._NT_y{Array{Float64,1}}}:
(y = 2.0)
(y = 4.0)
julia> pick((:y,:x))(c)
2-element IndexedTables.Columns{NamedTuples._NT_y_x{Float64,Int64},NamedTuples._NT_y_x{Array{Float64,1},Array{Int64,1}}}:
(y = 2.0, x = 1)
(y = 4.0, x = 2)
julia> pick((2,1))(c)
2-element IndexedTables.Columns{NamedTuples._NT_y_x{Float64,Int64},NamedTuples._NT_y_x{Array{Float64,1},Array{Int64,1}}}:
(y = 2.0, x = 1)
(y = …
```

make `pick` more useful

---

src/query.jl
test/test_core.jl

Right now the index columns become nameless after a `convertdim` if no name for the converted column is specified. I think keeping the names would be more useful, and might prompt users to look up "a way to change name of converted column" rather than prompt them to assume `convertdim` just loses the names.
The documentation says `name optionally specifies a new
name for the translated dimension.` and nothing about the behavior if it's omitted.

RFC: keep index column names in convertdim by default

---

REQUIRE
src/indexing.jl
test/test_core.jl

There are two optimizations here:
1) define `_in` for `Range` which was getting caught by `_in(::AbstractVector)` method and doing a slow lookup
2) Try to omit unnecessary columns (for which `_in` will always be true) in the second-pass check to see if indices fall inside the specified query.
Also, we now reexport `..` from IntervalSets which makes for a really nice indexing experience for Dates (you don't have to mention timestep of 1 millisecond, you can even give a Date range for a DateTime column and it will be closed range which includes the whole 2 days!). In general indexing with ClosedInterval is also faster than with ranges.

use IntervalSets for indexing

---

src/IndexedTables.jl
src/query.jl
src/utils.jl
test/test_query.jl

a first attempt at mapslices:
scalar version (i.e. if map function doesn't return an `IndexedTable`)
```julia
julia> using IndexedTables
julia> x=IndexedTable(Columns(a=[1,1,1,2,2],b=[1,2,3,1,2]),[1,2,3,4,5])
a  b │ 
─────┼──
1  1 │ 1
1  2 │ 2
1  3 │ 3
2  1 │ 4
2  2 │ 5
julia> mapslices(println, x, [1])
a  b │ 
─────┼──
1  1 │ 1
2  1 │ 4
a  b │ 
─────┼──
1  2 │ 2
2  2 │ 5
a  b │ 
─────┼──
1  3 │ 3
b │ 
──┼────────
1 │ nothing
2 │ nothing
3 │ nothing
julia> mapslices(println, x, [:b])
a  b │ 
─────┼──
1  1 │ 1
1  2 │ 2
1  3 │ 3
a  b │ 
─────┼──
2  1 │ 4
2  2 │ 5
a │ 
──┼────────
1 │ nothing
2 │ nothing
```
non-scalar version (i.e. function returns an IndexedTable):
```julia
julia> r=Ref(0);
julia> mapslices(x, [:a]) do slice
println("input:")
println(slice)
r[] += 1
n = length(slice) …
```

RFC/WIP: mapslices

---

src/IndexedTables.jl
src/columns.jl
src/utils.jl
test/test_core.jl

When constructing Columns with NamedTuples
before
```julia
julia> @btime IndexedTable(Columns(@NT(c=[1,2,3])), [1,3,2])
78.806 μs (113 allocations: 5.63 KiB)
```
after
```julia
julia> @btime IndexedTable(Columns(@NT(c=[1,2,3])), [1,3,2])
287.561 ns (14 allocations: 672 bytes)
```

Fix performance of IndexedTable constructor

---

src/IndexedTables.jl
src/indexing.jl
src/query.jl
src/utils.jl
test/test_core.jl
test/test_query.jl

See #63 
One minor annoyance:
`keys(t::IndexedTable, col::Union{Symbol,Int})` here returns a `Columns` with 1 vector. To get the column, you'd have to do `column(keys(t), col)`... This is so that `keys(t, cols...)`  always works by returning `Columns`. There's an alternative where you could make `keys(t, col::Tuple)` return columns but `keys(t, col::Symbol)` return the vector and not have `keys(t, cols...)`. Not sure which one to go with. @JeffBezanson what do you think?

WIP/RFC: Iteration API

---

src/IndexedTables.jl
src/indexing.jl
src/query.jl
src/utils.jl

Scalar indexing now converts the tuple to NamedTuple and does the lookup.

Don't force index Columns eltype to be Tuple

---

src/join.jl

When merging an IndexedTable into an empty one, we can just copy. Without this short-circuit check an invalid indexing is used.

Add empty dst check in _merge!

---

src/IndexedTables.jl

I'm running into errors without this because JuliaDB has precompile enabled.

Enable precompile

---

src/IndexedTables.jl
src/table.jl
test/test_core.jl

I tried implementing sorting for tables. I'm not sure about the API (for example, do we want `sort!`? do we want the ability to select the output?) and performance (`sortperm` seems 2x slower than `sort` yet it's pretty useful to sort a table wrt one column). In `sort!` I put two methods explicitly as the method without a `by` can be made more performant, not sure whether that's worth it though.
Example use:
```julia
julia> t = table(rand(10), rand(10), names = [:x, :y]);
julia> sort(t, rev = true) #reverse of standard lexicographic of Tuples
Table with 10 rows, 2 columns:
x         y
──────────────────
0.968263  0.690031
0.895568  0.736328
0.760924  0.492825
0.65686   0.267379
0.527287  0.212894
0.511014  0.991095
0.484162  0.544516
0.237564  0.731677
0.181119  0.702376
0.03072 …
```

RFC: sorting tables

---

src/reduce.jl
src/selection.jl
test/test_core.jl

I've tried a different implementation of #109 where I add a separate function `summarize`, that corresponds to dplyr's `summarise_each` and DataFrames' `aggregate`. It uses the usual `by`, `select` mechanism: see docstrings and tests for example usage.

Summarize all columns (second try)

---

src/reduce.jl

`groupby` is calling `f = init_func(f, data)` now, but the fallback for `init_func` was missing (see discussion in #111 ).

add missing init_func method

---

src/IndexedTables.jl
src/reshape.jl
test/test_core.jl

I've implemented `stack` and `unstack` for `NextTable` and `NDSparse` to change data from `wide` to `long` format and viceversa. In `stack` you choose the indexing columns with `by` and you select columns to stack with `select`.  Optional `variable` and `value` allow to choose name of column of identifiers and column of values. In `unstack`, you choose the indexing columns with `by` and you choose the column of identifiers and column of values with `variable` and `value` respectively (I tried to be as consistent as possible with DataFrames.
Example:
```julia
julia> iris
Table with 150 rows, 5 columns:
SepalLength  SepalWidth  PetalLength  PetalWidth  Species
─────────────────────────────────────────────────────────────
5.1          3.5         1.4          0.2         "setosa"
4.9 …
```

Stack/ unstack

---

src/columns.jl
src/table.jl
test/test_core.jl

An attempt to address #112 : if this approach is considered valid I can go on and add tests and documentation. Here I'm using as example the `hflights` dataset from [here](https://github.com/piever/JuliaDBTutorial).
```julia
julia> flights
Table with 227496 rows, 21 columns:
Columns:
──────────────────────────────────────────────────
1   Year               Int64
2   Month              Int64
3   DayofMonth         Int64
4   DayOfWeek          Int64
5   DepTime            DataValues.DataValue{Int64}
6   ArrTime            DataValues.DataValue{Int64}
7   UniqueCarrier      String
8   FlightNum          Int64
9   TailNum            String
10  ActualElapsedTime  DataValues.DataValue{Int64}
11  AirTime            DataValues.DataValue{Int64}
12  ArrDelay           DataValues.DataValue{Int64}
13 …
```

WIP/RFC: added SpecialSelector

---

src/reduce.jl
test/test_core.jl

This packages implements already a `view` on `Columns`: it simply makes a new `Columns` object whose columns are views of the parent columns. I think this is what should be passed to `groupby`. Now it is much easier to select columns from this object.
For example:
```julia
julia> t = table(@NT(a = [1, 1, 2, 2], b = rand(4), c = rand(4)))
Table with 4 rows, 3 columns:
a  b           c
───────────────────────
1  0.00334594  0.195242
1  0.390544    0.612741
2  0.923973    0.243861
2  0.630879    0.795554
julia> groupby(t, :a) do dd
mean(column(dd, :b).-column(dd, :c))
end
Table with 2 rows, 2 columns:
a  #3
────────────
1  -0.207046
2  0.257718
```
In a later issue we should discuss whether we can also allow the user to use values from `key` rather than `data` …

groupby revamped: column views and using key values

---

src/columns.jl
src/reduce.jl
test/test_core.jl

I hadn't updated `reduced_type` to work with `usekey` so a step of the naming process was failing.

fix  #124 : automatic naming for usekey = true

---

src/indexing.jl
src/ndsparse.jl
src/utils.jl
test/test_core.jl

This is a hack to detect if a buffer is shared. If it is it copies the NDSparse and then does flush!.

allow setindex! on arrays with shared data

---

src/join.jl
src/reduce.jl
src/selection.jl
src/table.jl
test/test_core.jl

Call `lowerselection` wherever needed to allow use of  `SpecialSelector` in `by` and `select` everywhere.

Fix #131: allow special selectors everywhere

---

src/table.jl
test/test_core.jl

This allows to call `getindex` and `view` with logical indexing (i.e. `t[[true, false]]`), whereas before it errored due to indexes being unsorted (which is incorrect, as this kind of indexing is always sorted).
I also allow unsorted indices if there are no primary keys. If there are primary keys, I can't quite decide whether we should remove those keys or error, I've left the error so far.

indexing usability improvements

---

src/flatten.jl
test/test_core.jl

A couple of usability improvements for `flatten`:
- Default to last column. It allows `groupby(identity, t, col) |> flatten`
- Do not error if eltype of column to flatten is non-iterable, but simply return the same table. This allow `groupby(f, t, col, flatten = true)` to work with greater generality.

flatten usability improvements

---

src/IndexedTables.jl
src/collect.jl
test/runtests.jl
test/test_collect.jl

Collect an iterable of `Tuples` or `NamedTuples` to a `Columns` object, without using inference. The `Columns` object is initialized with the type of the first element and progressively widened, should this type change.
I assume that the iterator iterates `Tuples` (or `NamedTuples`) always of the same length and, in the `NamedTuples` case, always with the same fieldnames.
The condition to trigger widening is that at least one field of the iterate tuple is not a subtype of the `eltype` of the corresponding  column.
Widening happens element-wise, meaning I perform `typejoin` on a field by field basis.
To work with `missing` in the future `typejoin` is not the correct operation, as:
```julia
julia> typejoin(Missing, Int)
Any
```
but `Base.promote_typejoin` should be sufficient to fix this. …

WIP: collect without inference

---

src/collect.jl
src/columns.jl
src/ndsparse.jl
src/selection.jl
test/test_core.jl

I've addressed the last issues from #135 (allowing the user to give a mix of `NamedTuples` with different fields that gets stored as `Vector{NamedTuples}`) and update `map` to use the new `collect_columns`.

map no longer relies on inference

---

src/tabletraits.jl
test/test_tabletraits.jl

I guess this happens all the time.

Avoid a too narrow value type in Dics in the table constructors in tabletraits.jl

---

src/collect.jl
src/columns.jl
src/utils.jl
test/test_collect.jl
test/test_core.jl

Implementation of the proposal in #139. I would mainly use `Columns{Pair}` as an internal object without documenting it/recommending it to the user as  I have not yet implemented all the methods for `Columns` on `Columns{Pair}` (though most should be there already) and some I'm not sure whether it makes sense to implement at all. OTOH the most relevant methods are there and are enough for the `collect_columns` implementation to work for column pairs.

Define and collect Columns{Pair}

---

src/collect.jl
test/test_collect.jl
test/test_core.jl

It also fixes `map` and `map_rows` as a consequence (as well as the breakage in JuliaDBMeta mentioned in #143 ).

fix collect_columns for empty iterator 

---

src/ndsparse.jl
src/selection.jl
src/table.jl
src/tabletraits.jl
test/test_core.jl
test/test_tabletraits.jl

This adds constructors and conversion methods to construct a `NextTable` or `NDSparse` from `Columns{<:Pair}` objects (the `first` field of the pair corresponding to primary keys), generalizes the iterator method for `table` to also accept iterators of tuples or pairs (in which case the `first` columns are primary, you can specify `presorted = true` if you know already they will be sorted).
`map` also allows functions that output a `Pair`, in which case the resulting table will have primary keys.
I think this should be the last tool needed to port `groupreduce` to the new `collect_columns` based implementation.

Construct table from pairs

---

REQUIRE
src/columns.jl
src/reduce.jl
test/test_core.jl

Now that we have new releases of OnlineStats[Base], we no longer need to wrap stats in a Series.

Remove Series wrappers for OnlineStats

---

src/ndsparse.jl
src/reduce.jl
test/test_core.jl

Also part of #139 . I've ported the `groupby` and `groupreduce` algorithm to the iterator approach. The core of the computation is now implemented in the `GroupBy` and `GroupReduce` iterators, but the algorithm being run is the same with two improvements:
- It no longer relies on inference
- If the returned object is not type stable, the column gets widened
The only caveat is that `groupreduce` with `f::Pair` used to work but I believe it was accidental (`f` was changed to `(f,)` if the inferred return type was not a `Tup`. I'm changing the test for that as I believe we only officially allow tuples or namedtuples of `Pair`. If you believe we should support `f::Pair` I can also do that.
I think the iterator approach allows some interesting future optimizations:
- `flatten` could be …

move group algorithms to collect_columns technique

---

src/collect.jl
test/test_collect.jl

Correct function to choose whether to widen correctly in all cases, correctly create `DataValueArray` even if column starts as regular `Array` but widens later.

More collect_column fixes

---

src/collect.jl
test/test_collect.jl

I'm adding a method to flatten and collect an iterator as `Columns`. It will be useful to optimize `groupby` with `flatten=true` (it will be done with just one pass over the data and the user will be able to save some allocations if the function in `groupby` returns an iterable rather than a table). I'm also needing it to convert `join` to the iterator approach.
It can either flatten an iterable of iterables or an iterable of pairs, where each pair is `key => iterable`.
Ideally it should have all the features of `flatten` and I hope could replace it eventually, but I'm not 100% sure what else `flatten` does other than flattening (in terms of naming or repeated keys).
I'm also not sure whether we want `collect_columns(x; flatten = false)`, it's handy but it seems we lose inferrability …

WIP/RFC: collect_columns_flattened

---

src/columns.jl
src/tabletraits.jl
test/test_core.jl
test/test_tabletraits.jl

Now `ndsparse` can accept an iterator of pairs and will build the corresponding `NDSparse` object. As with `table`, I've changed the default collection of iterator mechanism to use `collect_columns`. I'm also allowing the specification of index and data columns to be done with any selector / special selector, rather than just vector of symbols.
I've added `hascolumns` to check that extracting columns with a special selector will not error due to columns not being there (before it was `lenght(setdiff(idxcols, colnames(t))) > 0`, but this doesn't work for a general selector).

Add method to collect iterator of pairs as `ndsparse`

---

src/columns.jl
test/test_core.jl

Still lacks docs and tests but I was wondering if it is something people find useful. The strategy is:
- For column modificators that take two arguments other than the table (name and value or name and new name) add a `Pair` option, i. e. `setcol(t, name => value)`
- Add iterator version `setcol(t, itr) = foldl(setcol, t, itr)` as well as `setcol(t, itr...)` with the same meaning
- Add `transformcol` that combines `setcol` and `pushcol`: modify a column if it exists, add it otherwise. I have it implemented in JuliaDBMeta but I thought it made sense to have it here.
Example usage:
```julia
julia> t = table(rand(10), rand(10), rand(10), names = [:a, :b, :c]);
julia> renamecol(t, :a => :aa, :b => :bb)
Table with 10 rows, 3 columns:
aa        bb         c
───────────────────────────── …
```

Column modification usability improvement

---

src/join.jl
test/test_core.jl

The default merge behavior of PooledArray is to always convert the result to a non pooled type.
This overrides that behavior when the non pooled column is of reasonable length.

keep merged columns as PooledArrays when possible

---

src/columns.jl

Optimize `permute!` of columns of types `StringVector{String}` and `PooledArray`
Without this change:
```
julia> using IndexedTables, WeakRefStrings, PooledArrays, BenchmarkTools
julia> sv = StringVector{String}(convert(Vector{UInt8}, randstring(10^6+10)), UInt64[1:10:10^6;], ones(UInt32,10^5)*9);
julia> pv = PooledArray([randstring(5) for idx in 1:10^5]);
julia> cs = Columns(@NT(s=sv));
julia> cp = Columns(@NT(a=pv));
julia> p = randperm(10^5);
julia> @btime permute!(cs, p);
9.412 ms (200025 allocations: 9.50 MiB)
julia> @btime permute!(cp, p);
31.896 ms (199530 allocations: 12.54 MiB)
```
With this change:
```
julia> @btime permute!(cs, p);
1.553 ms (3 allocations: 781.36 KiB)
julia> @btime permute!(cp, p);
1.454 ms (2 allocations: 781.33 KiB)
```

optimize `permute!` for certain data types

---

src/utils.jl
test/runtests.jl
test/test_core.jl

to ensure they are serialized properly
fixes https://github.com/JuliaComputing/JuliaDB.jl/issues/198 and https://github.com/JuliaComputing/JuliaDB.jl/issues/199

keep WeakRefString in StringArray instead of Array

---

src/reduce.jl
test/test_core.jl

Based on [this thread](https://discourse.julialang.org/t/a-proposal-for-describe-of-a-dataframe/10254) in discourse: it allows a "stacked" version of summarize, which can be practical in some cases:
```julia
julia> t = table([1,2,3], [4,5,6], rand(3), names = [:a,:b,:c])
Table with 3 rows, 3 columns:
a  b  c
───────────────
1  4  0.171499
2  5  0.0396722
3  6  0.360162
julia> summarize((mean, std, eltype), t, stack=true)
Table with 3 rows, 4 columns:
variable  mean      std       eltype
─────────────────────────────────────
:a        2.0       1.0       Int64
:b        5.0       1.0       Int64
:c        0.190444  0.161083  Float64
```

Add stack option for summarize

---

src/columns.jl
src/utils.jl

by converting them to `StringArray{WeakRefString{UInt8}}`
Are there any compile time implications of this? @JeffBezanson

optimize `sortperm` on Columns of StringArrays

---

src/join.jl

naturaljoin and leftjoin are both defined and exported in the preceding for loop.
leftjoin! is not defined at all in this package.

Eliminate duplicate and invalid exports

---

src/utils.jl

This simplifies `ith_all`, which is called by `getindex`.  I see a slight speedup with  
```julia
@btime include("test/runtests.jl")
```
after the change.

Remove generated functions from getindex

---

.travis.yml
appveyor.yml
src/join.jl
src/ndsparse.jl
src/reduce.jl
src/selection.jl
test/test_collect.jl
test/test_core.jl

Removing deprecations that have been around for a year and many releases

remove deprecations

---

appveyor.yml
src/IndexedTables.jl
src/collect.jl
src/columns.jl
src/flatten.jl
src/join.jl
src/ndsparse.jl
src/reduce.jl
src/reshape.jl
src/selection.jl
src/table.jl

This is the first part of cleaning up the docs in IndexedTables and JuliaDB.  I'm doing this for a few reasons:
1.  JuliaDB docs have not been successfully building for some time.
1.  Many of the doctests fail for silly reasons (IndexedTables now uses the NamedTuples in Base, so tables print slightly different)
1. IndexedTables documents a lot of features in JuliaDB that aren't available in IndexedTables alone.
1. Much of the Documenter `@ref` syntax references pages in the online JuliaDB docs.
1. At the REPL, I want short-form documentation, leaving longer examples for the online documentation.
1. Shorter docstrings
- The docstrings are now a bit shorter and more appropriate for REPL usage.  Longer explanations of nuanced behavior/edge cases will go into the online docs for JuliaDB.
1. …

Round of doc cleanup

---

NEWS.md
README.md
REQUIRE
src/IndexedTables.jl
src/collect.jl
src/columns.jl
src/indexedtable.jl
src/indexing.jl
src/join.jl
src/ndsparse.jl
src/reshape.jl
src/selection.jl
src/tables.jl
src/tabletraits.jl
src/utils.jl
test/runtests.jl
test/test_collect.jl
test/test_core.jl
test/test_join.jl
test/test_missing.jl
test/test_tables.jl
test/test_tabletraits.jl
test/test_utils.jl

This builds on https://github.com/JuliaComputing/IndexedTables.jl/pull/199 (Tables.jl integration) and removes the dependency on DataValues.
The build/tests are running, but I'm still unsure of the consequences of performance, integration with IterableTables, etc.  
However, we are currently in a situation where TextParse loads missing data as `Union{T,Missing}` but then operations like table joins can introduce `DataValues`.

WIP: Transition to Missing

---

REQUIRE
src/IndexedTables.jl
src/collect.jl
src/columns.jl
src/flatten.jl
src/indexedtable.jl
src/indexing.jl
src/join.jl
src/ndsparse.jl
src/reduce.jl
src/reshape.jl
src/tables.jl
src/utils.jl
test/test_collect.jl
test/test_core.jl
test/test_utils.jl

This is extremely wip and it actually looks like it may be a massive work. The idea is to replace `Columns` with `StructVector` from the [StructArray](https://github.com/piever/StructArrays.jl) package. `StructVector` is strictly more general and a bit more performant.

Port to StructArrays

---

src/columns.jl

Otherwise when the function is a named tuple and the arguments are unnamed, it defaults to an array container for the result:
```julia
julia> IndexedTables._apply((+ = +,), (1,), (2,))
1-element Array{Int64,1}:
3
```
(see discussion at https://github.com/piever/StructArrays.jl/issues/41).

fix mixed tuple namedtuple method in _apply

---

REQUIRE
src/utils.jl

Now that `DataValueArray` supports the `undef` syntax (https://github.com/queryverse/DataValues.jl/pull/54) we no longer need to define `similar` with type piracy as the fallback to `DataValueArray{T}(undef, sz)` works.

remove datavaluearray piracy

---

REQUIRE
src/utils.jl

After https://github.com/JuliaData/WeakRefStrings.jl/pull/48 we don't need this pirate method anymore.

remove stringarray piracy

---

REQUIRE
src/IndexedTables.jl
src/tabletraits.jl
test/test_tabletraits.jl

TableTraits.jl sources *must* use ``DataValue`` in their row iterator to be compliant with the interface, even if the source uses ``Union{Missing,T}`` in its internal implementation. This PR adds that behavior.

Fix TableTraits source implementation

---

REQUIRE
src/columns.jl
src/join.jl

As discussed on Slack, this should prevent a large number of stringcmps in join.

Delete `cmpelts!` optimize `roweq` for PooledArrays, use it

---

src/reshape.jl
test/test_core.jl

The previous initialization was incorrect, putting either garbage or undefined values instead of `missing` for missing values in `unstack`, leading e.g. to https://github.com/JuliaComputing/JuliaDB.jl/issues/263
I've also changed the initialization to `similar(arrayof(typ), n)`  rather than `Array{typ}(undef, n)` for consistency with the rest of IndexedTables.

initialize arrays correctly in unstack

---

src/tables.jl
test/test_tables.jl

Tables uses `Tables.schema` to determine the type of the iterator which allows some optimizations, for example:
```julia
julia> using DataFrames, Tables
julia> df = DataFrame(x=1:10);
julia> Tables.schema(df)
Tables.Schema:
:x  Int64
```

define schema for an IndexedTable

---

REQUIRE
src/IndexedTables.jl
src/columns.jl
src/sortperm.jl
src/utils.jl

This moves the `fast_sortable` logic inside `sortperm_by` and `sortperm_fast`: I followed the scheme of https://github.com/piever/StructArrays.jl/pull/48 (which hopefully can be closed once this is merged) on `fast_sortable`: `StringArray{String}` goes to `StringArray{WeakRefString}`, `StringArray` gets pooled and on pooled arrays we use the same logic as what was implemented in PooledArrays (it needs the companion PR https://github.com/JuliaComputing/PooledArrays.jl/pull/21 to make sure we never end up doing the `fast_sortable` computation on PooledArrays twice). 
I hope this can restore good performance on `groupby` (end, more importantly, allows further performance tweaking without needing to change StructArrays), but have not benchmarked.
cc: @shashi @joshday

optimize sortpermby

---

src/reduce.jl
src/sortperm.jl

This has two advantages:
1. If data needs to be pooled, we only pool once and use the pooled data on `roweq`, which is much more efficient.
2.If the selection in `by` needs to compute something (i.e. `name => col => func`), we only compute it once (issue #165).

reuse pooling from sortpermby in grouping algorithms

---

REQUIRE
src/IndexedTables.jl
src/columns.jl
src/ndsparse.jl
src/reduce.jl

This uses the new `lazygroupmap` (bikeshedding on the name wanted) which is a low-level function to abstract the common mechanism in the grouping functions `groupby` and `groupreduce`. `lazygroupmap(f, keys, perm)`  returns an iterator that applies `f` to `(key, perm, idxs)` where `key` is the key of the group (as a struct), `perm` is the permutation and `idxs` is the range in `perm` that corresponds to the value `key`. Both `groupby` and `groupreduce` are special cases of this operation. `lazygroupmap` (implemented in https://github.com/piever/StructArrays.jl/pull/57/files, so tests will fail until that is merged and tagged) also takes care of optimizing comparison (to compute `idxs` only the refs of pooled data are compared) so it should have good performance.
EDIT: renamed …

Simplify grouping iteration mechanism

---

src/indexing.jl
test/test_core.jl

See https://github.com/JuliaComputing/IndexedTables.jl/issues/103 .
I didn't add `get!`. I'm not really sure what the appropriate value to add would be, since an element of ndsparse is a named tuple. If the default value is missing, it might make sense to add a named tuple with all values missing, but this wouldn't work in all cases.

Add haskey, get, tests

---

.travis.yml
REQUIRE
benchmark/join_benchmarks.jl
src/IndexedTables.jl
src/collect.jl
src/join.jl

This simplifies broadcast a bit and avoids relying on type inference for the result. As usual with this translation, I need to look at performance a bit before merging.

Move broadcast to iteration method

---

src/columns.jl
src/sortperm.jl
src/utils.jl

I've optimized `pool` in StructArrays directly so that we no longer need `compact_mem`. `pool` is fast for `StringArray{String}` but it also preserves the `eltype` (unlike `compact_mem`).

Remove compact_mem

---

src/utils.jl
test/test_core.jl
test/test_utils.jl

After the release of JuliaDB gets merged I think we might as well remove `_promote_op`: it's a private function that we no longer need.

remove `_promote_op`

---

src/indexedtable.jl

Fixes #231. Turns out in `IOContext` we also need `:limit => true` as only `:compact => true` would still print all elements for a long vector.

fix rendering bug for table of large vectors

---

src/IndexedTables.jl
src/columns.jl
src/ndsparse.jl
src/sortperm.jl
src/utils.jl
test/test_utils.jl

In a discussion on making DataFrames more lightweight (ref: https://github.com/JuliaData/DataFrames.jl/issues/1764), it was pointed out that StructArrays also got a bit of bloat (which feels unnecessary for people using it for things other than data analysis). I have a plan to get rid of the PooledArrays dependency and Requires use for WeakRefStrings, but it requires moving the "pooling" functionality back here, so I've renamed `pool` (that we took from StructArrays) to the old name of `compact_mem` (pool is wrong anyway as we are only pooling some columns) and moved the implementation here (in the future I will deprecate the implementation in StructArrays when I get rid of the dependencies).

rename pool back to compact_mem and implement here

---

src/IndexedTables.jl
src/columns.jl
src/indexedtable.jl
src/join.jl
src/utils.jl
test/test_utils.jl

Again, part of the plan to decouple IndexedTables from StructArrays internals. I'm also adding some small optimizations to avoid unnecessary allocations and to have things efficient also in the `Union{String, Missing}` case.

use permute!! or copyto! instead of fastpermute!

---

src/columns.jl
src/join.jl
test/test_join.jl

This fixes issue #237 by replacing the placeholder one normally gets with `rows(t, ())` with an array of correct length and `eltype`. I initially thought it was better to change the default behavior of `rows(t, ())` but that definitely deserves more discussion.

Fix #237 : join with empty data

---

src/IndexedTables.jl
src/columns.jl
src/indexedtable.jl
test/runtests.jl
test/test_core.jl

First part of #239. Here I'm deprecating `popcol(t, cols)` in favor of `select(t, Not(cols))` and `pushcol` and `setcol` are replaced by `transform`. I changes some generated code into normal code for readability as it is only needed for `rename!` now. I also did a bit of clean-up removing `ColDict` methods that were no longer needed.

 deprecate popcol, pushcol and setcol

---

src/IndexedTables.jl
src/columns.jl
src/reduce.jl
test/test_core.jl

This is the last part of #239, renaming `renamecol` to `renamecols` and deprecating `insertcol` to `insertcols` plus multiple columns version.
Two doubts:
1. Should the name be `renamecols` or just `rename`? After all we are obviously renaming columns (it wouldn't make to rename rows). Maybe we should just be consistent with `DataFrames` and call it `rename`.
2. I've interpreted the "multiple argument" version of `insertcols!` to behave as follows:
```julia
julia> t = table(rand(3), rand(3), rand(3), names = [:a,:b,:c])
Table with 3 rows, 3 columns:
a         b         c
────────────────────────────
0.509087  0.763431  0.557554
0.217274  0.801138  0.160908
0.462436  0.506603  0.921267
julia> insertcols(t, 2, :d => rand(3), :e => rand(3))
Table with 3 rows, 5 columns:
a         d         e …
```

Switch renamecol to rename and insertcol to insertcols, add multiple column version

---

src/columns.jl
test/test_core.jl

`foreach` uses the custom `foreach` implementation in IndexedTables which errors for iterators other than tuples (which is a pity, as we should support any pair iterator here).

use Base.foreach in column manipulations

---

src/flatten.jl

The code used to assume that one can push a plain tuple to a `StructArray{<:NamedTuple}` which is a behavior I would like to deprecate in StructArrays.

Iterate named tuples in mapslices

---

src/join.jl

Old behavior relied on StructArrays not checking that eltype and column named tuple have the same names.

Fix join when lkey and rkey have different names

---

src/indexing.jl

This is the last fix in view of the breaking StructArrays API changes (with this both IndexedTables and JuliaDB tests pass locally with the new StructArrays).

Allow pushing tuple indices to index_buffer

---

src/collect.jl
test/runtests.jl
test/test_collect.jl
test/test_core.jl

I'm planning to remove the special `StructArray(p::Pair)` constructor (it was a bit of an odd special case), so here I'm porting IndexedTables to use the normal approach for creating a `StructArray` of pairs: `StructArray{Pair{S, T}}((a, b))`.

stop using Pair constructor

---

src/IndexedTables.jl
src/columns.jl

There already is a `foreach` in IndexedTables that can do the same job as `foreachfield` from StructArrays so it's probably safer to not rely on external "utility" functions.

use IndexedTables rather than StructArrays utils

---

Project.toml

cc: @joshday , I think this should be good
cc: @davidanthoff I cleaned up the compat versions a little here
also cc: @piever to take a look

Bump version and clean up dependency compat

---

src/indexing.jl

Calling `pairs(NDSparse, idxs...)` used to throw: `ERROR: UndefVarError: Compat not defined`. This is fixed by this PR.
It might be worth noting that this did not break any test as this function is not tested.

Removed invalid reference to 'Compat'

---

Project.toml
src/IndexedTables.jl
src/columns.jl

So that IndexedTables and DataFrames can use the same special selectors. I'm leaving a buffer time with a deprecation warning for `Not` as JuliaDB accepts a multiargument version, impossible without type pirating InvertedIndices. When we drop the deprecation we can start using the InvertedIndices struct.
cc: @bkamins

Take special selectors from DataAPI

---

src/columns.jl

There was an outdated reference to `pushcol` in the `transform` docstring.

update transform and Not docstring

---

src/collect.jl

Now StructArrays (master, unreleased) passes the actual shape of the collected iterator to the initializer (to preserve it). This makes sure that the iterator is collected as a table backed by vectors (i.e. `AbstractArray{T, 1}`).

make IndexedTables compatible with StructArrays changes

---

src/columns.jl
test/test_core.jl

This should fix #279 , that is, make `select(tbl, (:newname => :existing,))` work.
One note is that it's now not possible to to select `:col => mapfn` when `!(mapFn isa Function)`. I don't think it's possible to resolve this succinctly/with dispatch (see: https://discourse.julialang.org/t/functions-and-callable-methods/2983). A workaround for users using functors like this would be `select(tbl, (mapFn.(tbl.columns.col),))`.
If the above is not acceptable, then alternatively I could special-case the selector `Pair{Symbol, Union{Symbol, Int, String, AbstractArray}}`, but this seems less general that ideal.

Fix newname => selector pairs

---

src/IndexedTables.jl
src/join.jl
test/test_join.jl
test/test_utils.jl

This moves an iterator that is only needed in IndexedTables from StructArrays. It is essentially a lazy join done via a merge sort between sorted iterators.
I'm planning to remove it from StructArrays in the next breaking release (see https://github.com/JuliaArrays/StructArrays.jl/pull/166), so I'm making this PR to make the update (from StructArrays 0.4 to 0.5) easier for IndexedTables.
On my machine I get some error during testing about WeakRefStrings, but they seem unrelated. (EDIT: never mind, CI passes here, I must have some dependencies devved locally.)

add join iterator

---

Project.toml
src/IndexedTables.jl
src/columns.jl
src/reduce.jl
src/selection.jl
test/test_core.jl

- Import stack from Base starting with Julia 1.9
- Switch from DataAPI.All to Cols and use values to extract from kwargs

Some general maintenance

---

src/indexedtable.jl
src/join.jl
test/test_utils.jl

In Julia 1.9.0, `permute!` is typically faster that the internal method `Base.permute!!`, thanks to https://github.com/JuliaLang/julia/pull/44941.
For indexed tables in particular, using the internal method `Base.permute!!` seems to give significant performance improvements for small arrays in exchange for moderate regressions for huge arrays when compared to `permute!` in microbenchmarks, though when doing slightly larger benchmarks using these functions as they are used in IndexedTables.jl, the improvements for `Base.permute!!` disappear.
```julia
using Random, BenchmarkTools, IndexedTables
small = table(rand(10), rand(10));
x = rand(10_000);
y = [randstring() for _ in 1:10_000];
big = table(x, y, rand(ComplexF64, 10_000), x, x, y);
x = rand(1_000_000);
y = [randstring() for _ in …
```

Replace `Base.permute!!` with `permute!`
