.travis.yml, src/NDSparseData.jl, test/runtests.jl, test/test_core.jl, test/test_query.jl, test/test_utils.jl
Added tests and enabled coverage upload from travis builds.
The repo probably needs to be enabled at coveralls.io and codecov.io.
=> improve tests and coverage

src/NDSparseData.jl, test/test_core.jl
=> fix #11 step range indexing

REQUIRE, src/IndexedTables.jl, src/columns.jl, src/indexing.jl, src/utils.jl, test/test_core.jl
=> 0.6 compat

.travis.yml, REQUIRE, src/IndexedTables.jl, src/columns.jl, src/join.jl, src/utils.jl, test/test_core.jl
=> Allow arbitrary return types in map and broadcast

src/query.jl, test/test_query.jl
much more efficient to not create an IndexedTable with 1 row...
=> pass pair to f in mapslices(f, t, ())

test/runtests.jl
I like that the test results all appear in one table with this. Purely aesthetic, so if you like it some other way, just close this :)
=> Add toplevel testset

src/columns.jl, src/table.jl, test/test_core.jl
Work in progress implementation of a view of NextTable. I still have a couple of doubts that I'll leave as comments to the code.
=> WIP: Added view of NextTable

README.md
The readme is a bit out of date.  This PR does some cleanup, removes most of the content, and instead points people towards the JuliaDB API reference.  Thoughts?
=> WIP: Readme

src/reduce.jl
Ref: https://github.com/JuliaLang/METADATA.jl/pull/13018#issuecomment-360324963
=> Fix ambiguous Series method

src/tabletraits.jl
This will use ``DataValueArray`` for columns that have missing data during construction via the iterable tables interface. Currently one ends up with ``Vector{DataValue}``, which seems not ideal. I was originally hesitant to use ``DataValueArray`` here because I didn't want to "shove" it onto IterableTables.jl, but it seems that you guys are using it in any case already, so this might make sense?
=> Use DataValueArray for TableTraits integration

src/columns.jl, test/test_core.jl
See comment [here](https://github.com/JuliaComputing/JuliaDB.jl/pull/141#discussion_r170660525).
=> allow column selection by regexes

REQUIRE, src/columns.jl, src/reduce.jl, test/REQUIRE, test/test_core.jl
Fixes for the new design of OnlineStats and OnlineStatsBase, which now have metadata PRs.
=> WIP: updates for redesigned OnlineStats[Base]

REQUIRE, src/columns.jl, src/reduce.jl, test/REQUIRE, test/test_core.jl
Reverts JuliaComputing/IndexedTables.jl#142
I think I figured out a way to handle OnlineStats changes with deprecations.
=> Revert "WIP: updates for redesigned OnlineStats[Base]"

REQUIRE, src/collect.jl, src/columns.jl, src/ndsparse.jl, src/reduce.jl, src/selection.jl, src/sortperm.jl, src/table.jl, src/utils.jl, test/test_core.jl
supersedes #144 and #152 rebased against current master
=> StringArray, PooledArray with Dict pool, and performance improvements

src/columns.jl, src/utils.jl
Improves run time greatly for tuples of length >= 15
=> WIP: Generated functions for `Tuple`s

README.md
the ndsparse example still doesn't work
=> update readme for julia 1.0

REQUIRE, src/IndexedTables.jl, src/collect.jl, src/columns.jl, src/flatten.jl, src/join.jl, src/ndsparse.jl, src/reduce.jl, src/reshape.jl, src/selection.jl, src/table.jl, src/tabletraits.jl, src/utils.jl, test/REQUIRE, test/test_core.jl
- Replace OnlineStats dependency with OnlineStatsBase
- Change `NextTable` -> `IndexedTable` (with deprecation warning for `NextTable`)
=> Replace: OnlineStats -> OnlineStatsBase, Change name: NextTable -> IndexedTable

src/join.jl, test/test_core.jl
See https://github.com/JuliaComputing/IndexedTables.jl/issues/201
=> Add support for broadcast of unary functions

src/utils.jl
Most of the sorting code now lives in StructArrays and is no longer needed here. The `sortperm_fast` method for vectors of integers made it to Base (in `sortperm`) so we don't need to reimplement it here.
=> remove unnecessary sorting code

benchmark/join_benchmarks.jl, src/collect.jl, src/join.jl
In particular need to use inference for the empty collection case (just like Base), but without erroring if it fails).
=> extra join cleanup

.gitignore, Project.toml
Mainly moving dependencies only required in tests as extras and removing compatibility for Julia 2.0
=> Minor project fixes

src/tabletraits.jl
=> Remove try catch from fallback table constructor to not mask errors

src/join.jl
fix minor typo in docs of merge method
=> fix typo in docs
